import SideBar from './components/sidebar'
import './globals.css'
import { personalData } from './data/date'
import Footer from './components/footer'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body className='flex flex-col sm:flex-row '>
        <SideBar data={personalData}/>
        <main className='grow-full  p-16  sm:p-16 w-full sm:basis-2/3  ml-auto' > 
        {children}
        <Footer/>
        </main>
        
        </body>
    </html>
  )
}
